# ~/.config/fish/config.fish

# Only execute this file once per shell
set -q __fish_config_sourced; and exit
set -g __fish_config_sourced 1

# ============================================================================
# Interactive Shell Configuration
# ============================================================================
if status is-interactive
    # Greeting
    set -g fish_greeting "Welcome to fish, the friendly interactive shell!"

    # ========================================================================
    # Prompt Configuration (Tide)
    # ========================================================================
    set -g tide_left_prompt_items time pwd git
    set -g tide_right_prompt_items status cmd_duration jobs python kubectl toolbox terraform aws

    # ========================================================================
    # Aliases
    # ========================================================================
    alias less='less -r'
    alias mkdir='mkdir -pv'
    alias grep='grep --color=auto'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias h='history'
    alias j='jobs -l'
    alias ping='ping -c 5'
    alias pingfast='ping -c 100 -s.2'
    alias ls='lsd'
    alias now='date +"%T"'
    alias vi=nvim
    alias vim=nvim

    # ========================================================================
    # Key Bindings
    # ========================================================================
    bind \e\x7f backward-kill-word

    # ========================================================================
    # Tool Integration
    # ========================================================================
    
    # Docker completions
    if command -q docker
        if test ! -f ~/.config/fish/completions/docker.fish
            mkdir -p ~/.config/fish/completions
            docker completion fish >~/.config/fish/completions/docker.fish
        end
    end

    # direnv
    if command -q direnv
        set -g direnv_fish_mode disable_arrow
        direnv hook fish | source
    end

    # jenv (Java version management)
    if command -q jenv
        jenv init - | source
    end
end

# ============================================================================
# Login Shell Configuration
# ============================================================================
if status is-login
    # Login shell initialization
    # Add any login-specific configuration here
end


# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/9xgdmqwl0hbxi3ppp4bdkwwixdglks00-hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases

    # Interactive shell initialisation
    set -g fish_greeting "Welcome to the fish, the friendly interactive shell! Please note that this shell is managed by nix..."

    # Set up tide prompt
    set -g tide_left_prompt_items time pwd git
    set -g tide_right_prompt_items status cmd_duration jobs python kubectl toolbox terraform aws

    # Common aliases
    alias less='less -r'
    alias mkdir='mkdir -pv'
    alias grep='grep --color=auto'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias h='history'
    alias j='jobs -l'
    alias ping='ping -c 5'
    alias pingfast='ping -c 100 -s.2'
    alias ls='lsd'
    alias now='date +"%T"'
    alias vi=nvim
    alias vim=nvim

    # Key bindings
    bind \e\x7f backward-kill-word

    # Set up docker completion
    if command -q docker
        if [ ! -f ~/.config/fish/completions/docker.fish ]
            docker completion fish >~/.config/fish/completions/docker.fish
        end
    end

    # nix-direnv will add the `direnv hook fish | source` line, but this disables arrow key navigation
    set -g direnv_fish_mode disable_arrow

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/mjcramer/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/p1hdzfxppxjp22r71fgfwghziz4axmnq-direnv-2.36.0/bin/direnv hook fish | source

end

# Set up jenv for managing JDK paths
if test (which jenv)
    jenv init - | source
end
